wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.2
adversarial:
  desc: null
  value: true
batch:
  desc: null
  value: 32
conv:
  desc: null
  value: true
epoch:
  desc: null
  value: 1500
generate:
  desc: null
  value: false
img_wd:
  desc: null
  value: /home/aogorodnikov/data_aae
input_dim:
  desc: null
  value:
  - 144
  - 144
  - 3
itsr:
  desc: null
  value: false
latent_dim:
  desc: null
  value: 32
out:
  desc: null
  value: /home/aogorodnikov/aae/
plot:
  desc: null
  value: false
recons:
  desc: null
  value: false
train:
  desc: null
  value: true
verbose:
  desc: null
  value: true
